algoritmo "exercicio_07"
var
     dobro, terca, N: real
inicio
      escreva ("Digite um número: ")
      leia (N)
      dobro <- N * 2
      terca <- N /3
      escreval ("O dobro de ", N, " é ", dobro:6:2)
      escreval ("A terça parte de ", N, " é ", terca:6:2)

fimalgoritmo



7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
sua terça parte.
Ex:
Digite um número: 3.5
O dobro de 3.5 é 7.0
A terça parte de 3.5 é 1.1666