algoritmo "exercico_06"
var
     N, Suc, Ant: inteiro
inicio
      escreva ("Digite um número: ")
      leia (N)
      Suc <- N + 1
      Ant <- N - 1
      
      escreval ("O antecessor de ", N, " é ", Ant)
      escreval ("O sucessor de ", N, " é ", Suc)

fimalgoritmo




6) Faça um programa que leia um número inteiro e mostre o seu antecessor e seu
sucessor.
Ex:
Digite um número: 9
O antecessor de 9 é 8
O sucessor de 9 é 10