algoritmo "exercicio_05"
var
    N1, N2, media: real
inicio
      escreva ("Digite a primeira nota: ")
      leia (N1)
      escreva ("Digite a segunda nota: ")
      leia (N2)
      media <- N1 + N2
      escreva ("A média entre ", N1, " e ", N2, " é igual a ", media)

fimalgoritmo



5) Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
na tela a sua média na disciplina.
Ex:
Nota 1: 4.5
Nota 2: 8.5
A média entre 4.5 e 8.5 é igual a 6.5